apiVersion: v1
kind: Service
metadata:
  name: prime-video-clone
spec:
  type: {{ .Values.service.type }}
  selector:
    app: prime-video-clone
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 3000
